In [23]:
import numpy as np
import matplotlib.pyplot as plt
from zernike import RZern, FitZern

pol = RZern(1)
L, K = 360, 100
ip = FitZern(pol, L, K)

pol.make_pol_grid(ip.rho_j, ip.theta_i)
c_true = np.random.normal(size=pol.nk)
Phi = pol.eval_grid(c_true)
c_hat = ip.fit(Phi)
R = np.zeros((pol.nk, 3))
R[:, 0] = c_true
R[:, 1] = c_hat
R[:, 2] = np.abs(c_true - c_hat)
print(R)
np.linalg.norm(c_true - c_hat)/np.linalg.norm(c_true)

[[ 2.78266198e-01  2.78266198e-01  5.55111512e-17]
 [ 8.87143854e-01  8.87123474e-01  2.03800733e-05]
 [-7.09224179e-02 -7.09207886e-02  1.62927813e-06]]


2.1925917679640225e-05

In [26]:
pol.eval_a(c_true, 0.5, np.pi)

-0.608877656154573